name: Build

on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main

jobs:
 build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
      #    - name: Set up Cygwin
      #      uses: egor-tensin/setup-cygwin@v4
      #      if: matrix.os == 'windows-latest'
      #      with:
      #        packages: gcc-g++
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install LLVM (brew)
      run: brew install llvm@17
    - name: Set LLVM Environment Variables
      run: |
        LLVM_PREFIX=$(brew --prefix llvm)
        echo "LLVM_PREFIX=$LLVM_PREFIX" >> $GITHUB_ENV
        echo "PATH=$LLVM_PREFIX/bin:$PATH" >> $GITHUB_ENV
        echo "LDFLAGS=-L$LLVM_PREFIX/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I$LLVM_PREFIX/include" >> $GITHUB_ENV
    - name: Setup meson and ninja
      run: pip install meson ninja
    - name: Prepare Build
      run: meson setup build
    - name: Run Build
      run: meson compile -v -C build
